Fix error in to_table()
I am using astropy 3.0.1 and numpy 1.14.3. Without this patch,
`schedule.to_table()` produces this exception:

    TypeError: only dimensionless scalar quantities can be converted to Python scalars